image: maven:3.6-jdk-11

before_script:
  - hostname
  - whoami
  - env

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

stages:
  - test
  - package
  - publish

test:
  stage: test
  only:
    - develop
    - master
  script:
    - mvn clean test -e $MAVEN_CLI_OPTS
  artifacts:
    reports:
      junit:
        - ./target/surefire-reports/TEST-*.xml

package:
  stage: package
  needs:
    - test
  only:
    - develop
    - master
  script:
    - mvn package
  artifacts:
    paths:
      - target/distribution

publish-maven:
  stage: publish
  needs:
    - test
    - package
  script:
    - 'mvn deploy -s src/main/assembly/ci_settings.xml'
  only:
    - master

publish-docker:
  stage: publish
  needs:
    - test
    - package
  image: docker:19.03.8
  only:
    - master
  extends: .with-dind
  script:
    - docker info
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

.with-dind:
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
  services:
    - name: docker:19.03.8-dind
      command:
        - /bin/sh
        - -c
        - |
          echo "$CI_SERVER_TLS_CA_FILE" > /etc/ssl/certs/ca-cert-gitlab.pricefx.eu.crt || exit
          dockerd-entrypoint.sh || exit